[project]
name = "zolt-update"

[dependencies]
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-repository" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = { versionRef = "junit-platform" }
