[project]
name = "api"
main = "com.example.workspace.api.ApiApplication"

[dependencies]
"com.example.workspace:core" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"
