[project]
name = "zolt-build"

[dependencies]
"sh.zolt:zolt-junit-client" = { workspace = true }
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-repository" = { workspace = true }
"sh.zolt:zolt-resolve" = { workspace = true }
"sh.zolt:zolt-test-model" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.api]
"sh.zolt:zolt-framework-api" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"

[test.suites.test-execution]
classes = [
    "sh.zolt.build.profile.TestProfileMergerTest",
    "sh.zolt.build.profile.TestProfileSummaryFormatterTest",
    "sh.zolt.build.junit.PlainJunitWorkerPoolRunnerTest",
]
