[project]
name = "zolt-junit-worker"
main = "sh.zolt.junit.JunitLauncherWorker"

[dependencies]
"sh.zolt:zolt-junit-client" = { workspace = true }
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-test-model" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.14.4"

[package]
mode = "uber-jar"
