[workspace]
name = "zolt"

[workspace.members]
default = ["apps/zolt"]
include = ["apps/*", "modules/*"]

[workspace.project]
group = "sh.zolt"
version = "0.1.0-SNAPSHOT"
java = 21
license = "Apache-2.0"

[versions]
junit-platform = "1.14.4"
quarkus = "3.39.1"
tomlj = "1.1.1"

[toolchain.java]
distribution = "graalvm-community"
features = ["native-image"]
policy = "require-managed"

[coverage]
line = 88
branch = 74
