[project]
name = "zolt-workspace"

[dependencies]
"sh.zolt:zolt-build" = { workspace = true }
"sh.zolt:zolt-framework-api" = { workspace = true }
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-native-image" = { workspace = true }
"sh.zolt:zolt-publish" = { workspace = true }
"sh.zolt:zolt-repository" = { workspace = true }
"sh.zolt:zolt-resolve" = { workspace = true }
"sh.zolt:zolt-test-model" = { workspace = true }
"sh.zolt:zolt-test-runtime" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"
