[project]
name = "micronaut-http"
version = "0.1.0"
group = "com.example"
java = 21
main = "com.example.micronaut.DemoApplication"

[platforms]
"io.micronaut.platform:micronaut-platform" = "4.10.12"

[dependencies]
"ch.qos.logback:logback-classic" = { managed = true }
"io.micronaut.serde:micronaut-serde-jackson" = { managed = true }
"io.micronaut:micronaut-http-server-netty" = { managed = true }
"io.micronaut:micronaut-runtime" = { managed = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"

[dependencies.processor]
"io.micronaut.serde:micronaut-serde-processor" = { managed = true }
"io.micronaut:micronaut-http-validation" = { managed = true }
"io.micronaut:micronaut-inject-java" = { managed = true }
