[project]
name = "zolt-policy"

[dependencies]
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"
