[project]
name = "app"
main = "com.example.large.app.LargeApplication"

[dependencies]
"com.example.large:service" = { workspace = true }
"commons-io:commons-io" = "2.20.0"

[dependencies.test]
"org.junit.jupiter:junit-jupiter" = "5.11.4"
