[project]
name = "zolt-sbom"

[dependencies]
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-repository" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.test]
"com.networknt:json-schema-validator" = "2.0.7"
"org.junit.platform:junit-platform-console-standalone" = "1.14.4"
