[project]
name = "zolt-toml"

[dependencies]
"sh.zolt:zolt-model" = { workspace = true }

[dependencies.api]
"org.tomlj:tomlj" = "1.1.1"

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"
