[project]
name = "zolt-test-runtime"

[dependencies]
"sh.zolt:zolt-build" = { workspace = true }
"sh.zolt:zolt-framework-api" = { workspace = true }
"sh.zolt:zolt-junit-client" = { workspace = true }
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-resolve" = { workspace = true }
"sh.zolt:zolt-test-model" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"

[test.suites.test-execution]
classes = [
    "sh.zolt.build.coverage.CoverageServiceTest",
    "sh.zolt.build.coverage.CoverageServiceValidationTest",
    "sh.zolt.build.testruntime.execution.CurrentWorkerClasspathTest",
    "sh.zolt.build.testruntime.execution.FrameworkTestSelectionMapperTest",
    "sh.zolt.build.testruntime.execution.JunitConsoleArgumentsTest",
    "sh.zolt.build.testruntime.execution.JunitLauncherClasspathTest",
    "sh.zolt.build.testruntime.execution.TestConsoleFailureHandlerTest",
    "sh.zolt.build.testruntime.execution.TestRuntimeInputBuilderTest",
    "sh.zolt.build.testruntime.TestRuntimeValueObjectsTest",
    "sh.zolt.build.testruntime.TestRunServiceFailureTest",
    "sh.zolt.build.testruntime.TestRunServiceFrameworkRunnerTest",
    "sh.zolt.build.testruntime.TestRunServiceRuntimeOptionsTest",
    "sh.zolt.build.testruntime.TestRunServiceSelectionTest",
    "sh.zolt.build.testruntime.TestRunServiceTest",
]
