[project]
name = "zolt-repository"

[dependencies]
"sh.zolt:zolt-model" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = { versionRef = "junit-platform" }
