[project]
name = "zolt-config"

[dependencies]
"org.tomlj:tomlj" = { versionRef = "tomlj" }
"sh.zolt:zolt-model" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = { versionRef = "junit-platform" }
