[project]
name = "zolt-config"

[dependencies]
"org.tomlj:tomlj" = "1.1.1"
"sh.zolt:zolt-model" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"
