[project]
name = "zolt-explain"

[dependencies]
"org.tomlj:tomlj" = { versionRef = "tomlj" }
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-repository" = { workspace = true }
"sh.zolt:zolt-resolve" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = { versionRef = "junit-platform" }
