[project]
name = "zolt-quarkus"

[dependencies]
"sh.zolt:zolt-build" = { workspace = true }
"sh.zolt:zolt-framework-api" = { workspace = true }
"sh.zolt:zolt-ide" = { workspace = true }
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-repository" = { workspace = true }
"sh.zolt:zolt-resolve" = { workspace = true }
"sh.zolt:zolt-test-model" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.provided]
"io.quarkus:quarkus-builder" = { versionRef = "quarkus" }
"io.quarkus:quarkus-core-deployment" = { versionRef = "quarkus" }
"io.quarkus:quarkus-junit" = { versionRef = "quarkus" }
"io.smallrye:jandex" = "3.6.0"

[dependencies.test]
"io.quarkus:quarkus-arc-deployment" = { versionRef = "quarkus", exclude = ["io.quarkus:quarkus-arc", "io.quarkus:quarkus-arc-dev", "io.quarkus:quarkus-arc-test-supplement", "io.quarkus:quarkus-arc-test-supplement-decorator", "io.quarkus:quarkus-core-deployment", "io.quarkus:quarkus-devui-deployment-spi", "io.quarkus:quarkus-smallrye-context-propagation-spi", "io.quarkus.arc:arc-processor"] }
"io.quarkus:quarkus-bootstrap-app-model" = { versionRef = "quarkus" }
"io.quarkus:quarkus-bootstrap-core" = { versionRef = "quarkus" }
"io.quarkus:quarkus-core" = { versionRef = "quarkus" }
"io.quarkus:quarkus-fs-util" = "1.4.2"
"io.quarkus:quarkus-test-common" = { versionRef = "quarkus", exclude = ["commons-io:commons-io", "io.quarkus:quarkus-bootstrap-gradle-resolver", "io.quarkus:quarkus-bootstrap-maven-resolver", "io.quarkus:quarkus-core-deployment", "io.rest-assured:rest-assured", "io.smallrye:jandex", "org.jboss.logging:commons-logging-jboss-logging"] }
"io.smallrye.config:smallrye-config-core" = "3.18.2"
"org.junit.platform:junit-platform-console-standalone" = { versionRef = "junit-platform" }
"org.wildfly.common:wildfly-common" = "2.0.1"

[test.runtime]
jvmArgs = ["-Djava.util.logging.manager=org.jboss.logmanager.LogManager"]
