package sh.zolt.explain.emit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.manifest.LocalId;
import sh.zolt.manifest.ProjectVersion;
import sh.zolt.manifest.WorkspaceMemberPattern;
import sh.zolt.manifest.authored.AuthoredBuildConfiguration;
import sh.zolt.manifest.authored.AuthoredManifest;
import sh.zolt.manifest.authored.AuthoredPackaging;
import sh.zolt.manifest.authored.AuthoredProjectIdentity;
import sh.zolt.manifest.authored.AuthoredWorkspace;
import sh.zolt.manifest.authored.AuthoredWorkspaceMembers;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;

final class DraftWorkspaceRendererTest {
    @Test
    void renderBundleIncludesReviewItemsHeadersAndMemberBodies() {
        String rendered = new DraftWorkspaceRenderer().render(workspaceDraft(), new FakeManifestRenderer());

        assertTrue(rendered.startsWith("# Draft Zolt workspace generated by `zolt explain --emit-toml`"),
                () -> rendered);
        assertTrue(rendered.contains("# Review items:\n"
                + "# Root aggregator declares dependencies that must move into members.\n"), () -> rendered);
        assertTrue(rendered.contains("# --- zolt.toml (workspace root) ---\n"
                + "[workspace]\n"
                + "name = \"shop\"\n"
                + "members = [\"app\", \"lib\"]\n"), () -> rendered);
        assertTrue(rendered.contains("# --- app/zolt.toml ---\n"
                + "# Review items:\n"
                + "# app has a classifier dependency to review.\n"
                + "\n"
                + "[project]\n"
                + "name = \"app\"\n"), () -> rendered);
        assertTrue(rendered.contains("# --- lib/zolt.toml ---\n"
                + "[project]\n"
                + "name = \"lib\"\n"), () -> rendered);
        assertTrue(rendered.endsWith("\n"), () -> rendered);
    }

    @Test
    void renderDocumentsSplitsRootAndMembersWithTrailingNewlines() {
        List<DraftZoltTomlDocument> documents =
                new DraftWorkspaceRenderer().renderDocuments(workspaceDraft(), new FakeManifestRenderer());

        assertEquals(List.of("zolt.toml", "app/zolt.toml", "lib/zolt.toml"),
                documents.stream().map(DraftZoltTomlDocument::relativePath).toList());
        assertTrue(documents.get(0).contents().contains(
                "# Draft Zolt workspace generated by `zolt explain --emit-toml`"), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().contains("# Review items:\n"
                + "# Root aggregator declares dependencies that must move into members.\n"), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().contains("[workspace]\n"), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().endsWith("\n"), documents.get(0)::contents);

        assertTrue(documents.get(1).contents().startsWith("# Review items:\n"
                + "# app has a classifier dependency to review.\n"
                + "\n"
                + "[project]\n"), documents.get(1)::contents);
        assertTrue(documents.get(1).contents().endsWith("\n"), documents.get(1)::contents);
        assertTrue(documents.get(2).contents().startsWith("[project]\n"), documents.get(2)::contents);
        assertTrue(documents.get(2).contents().endsWith("\n"), documents.get(2)::contents);
    }

    @Test
    void draftDocumentsRejectBlankPathAndNullContents() {
        IllegalArgumentException blankPath = assertThrows(
                IllegalArgumentException.class,
                () -> new DraftZoltTomlDocument(" ", ""));
        assertEquals("A draft zolt.toml document must have a non-blank relative path.", blankPath.getMessage());

        IllegalArgumentException nullContents = assertThrows(
                IllegalArgumentException.class,
                () -> new DraftZoltTomlDocument("app/zolt.toml", null));
        assertEquals("A draft zolt.toml document must have contents.", nullContents.getMessage());
    }

    @Test
    void workspaceMembersRejectBlankPath() {
        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> new DraftWorkspace.Member("\t", draft("blank")));

        assertEquals("A workspace member must have a non-blank relative path.", exception.getMessage());
    }

    private static DraftWorkspace workspaceDraft() {
        return new DraftWorkspace(
                workspaceRoot(),
                List.of(
                        new DraftWorkspace.Member(
                                "app",
                                new DraftZoltToml(
                                        project("app"),
                                        List.of("app has a classifier dependency to review."))),
                        new DraftWorkspace.Member("lib", draft("lib"))),
                List.of("Root aggregator declares dependencies that must move into members."));
    }

    private static DraftZoltToml draft(String name) {
        return new DraftZoltToml(project(name), List.of());
    }

    /** The root document a drafted workspace emits: members included, {@code default} left unauthored. */
    private static AuthoredManifest workspaceRoot() {
        return DraftManifests.workspaceRoot(new AuthoredWorkspace(
                new LocalId("shop"),
                new AuthoredWorkspaceMembers(
                        List.of(new WorkspaceMemberPattern("app"), new WorkspaceMemberPattern("lib")),
                        List.of(),
                        Optional.empty()),
                Optional.empty()));
    }

    private static AuthoredManifest project(String name) {
        List<String> notes = new ArrayList<>();
        return DraftManifests.project(
                DraftManifests.identity(
                        name, Optional.of("com.example"), Optional.of("1.0.0"), Optional.of(21), notes),
                DraftManifests.metadata(Optional.empty(), notes),
                Optional.empty(),
                Optional.empty(),
                Optional.empty(),
                AuthoredBuildConfiguration.empty(),
                Optional.empty(),
                AuthoredPackaging.empty());
    }

    /**
     * Stands in for the canonical writer. A workspace root and a project are the same authored shape in
     * the final language, so the fake branches on the {@code [workspace]} domain to give each document
     * kind a body the splitting and labelling assertions can tell apart.
     */
    private static final class FakeManifestRenderer implements AuthoredManifestRenderer {
        @Override
        public String render(AuthoredManifest manifest) {
            return manifest.workspace()
                    .map(FakeManifestRenderer::renderWorkspace)
                    .orElseGet(() -> renderProject(manifest));
        }

        private static String renderWorkspace(AuthoredWorkspace workspace) {
            String members = workspace.members().include().stream()
                    .map(member -> "\"" + member.value() + "\"")
                    .collect(Collectors.joining(", "));
            return """
                    [workspace]
                    name = "%s"
                    members = [%s]
                    """.formatted(workspace.name().value(), members);
        }

        private static String renderProject(AuthoredManifest manifest) {
            AuthoredProjectIdentity identity = manifest.project().orElseThrow().identity();
            return """
                    [project]
                    name = "%s"
                    version = "%s"
                    """.formatted(
                    identity.name().value(),
                    identity.version().map(ProjectVersion::value).orElse(""));
        }
    }
}
