package sh.zolt.explain.emit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.explain.gradle.GradleInspectionResult;
import sh.zolt.explain.gradle.GradleStaticProjectInspector;
import sh.zolt.explain.maven.MavenInspectionResult;
import sh.zolt.explain.maven.MavenStaticProjectInspector;
import sh.zolt.manifest.authored.AuthoredManifest;
import sh.zolt.manifest.authored.AuthoredProjectIdentity;
import sh.zolt.manifest.authored.AuthoredWorkspace;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

final class EmitRendererTest {
    @TempDir
    private Path tempDir;

    @Test
    void mavenSingleProjectCanRenderTextAndDocument() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.acme</groupId>
                  <artifactId>demo</artifactId>
                  <version>1.0.0</version>
                </project>
                """);
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(tempDir);
        EmitRenderer renderer = renderer();

        String text = renderer.renderMaven(result);
        List<DraftZoltTomlDocument> documents = renderer.renderMavenDocuments(result);

        assertTrue(text.startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"), () -> text);
        assertTrue(text.contains("name = \"demo\""), () -> text);
        assertEquals(1, documents.size());
        assertEquals("zolt.toml", documents.get(0).relativePath());
        assertTrue(documents.get(0).contents().contains("name = \"demo\""), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().endsWith("\n"), documents.get(0)::contents);
    }

    @Test
    void mavenReactorCanRenderWorkspaceTextAndSplitDocuments() throws IOException {
        writeMavenReactor();
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(tempDir);
        EmitRenderer renderer = renderer();

        String text = renderer.renderMaven(result);
        List<DraftZoltTomlDocument> documents = renderer.renderMavenDocuments(result);

        assertTrue(text.contains("# --- zolt.toml (workspace root) ---\n[workspace]\nname = \"demo-parent\"\n"),
                () -> text);
        assertTrue(text.contains("# --- service/zolt.toml ---\n"), () -> text);
        assertTrue(text.contains("[project]\nname = \"service\"\n"), () -> text);
        assertEquals(List.of("zolt.toml", "service/zolt.toml"),
                documents.stream().map(DraftZoltTomlDocument::relativePath).toList());
        assertTrue(documents.get(0).contents().contains("[workspace]\nname = \"demo-parent\"\n"),
                documents.get(0)::contents);
        assertTrue(documents.get(1).contents().contains("[project]\nname = \"service\"\n"),
                documents.get(1)::contents);
    }

    @Test
    void gradleSingleProjectCanRenderTextAndDocument() throws IOException {
        Files.writeString(tempDir.resolve("settings.gradle"), "rootProject.name = 'gradle-demo'\n");
        Files.writeString(tempDir.resolve("build.gradle"), """
                plugins { id 'java' }
                group = 'com.acme'
                version = '1.2.3'
                """);
        GradleInspectionResult result = new GradleStaticProjectInspector().inspect(tempDir);
        EmitRenderer renderer = renderer();

        String text = renderer.renderGradle(result);
        List<DraftZoltTomlDocument> documents = renderer.renderGradleDocuments(result);

        assertTrue(text.contains("name = \"gradle-demo\""), () -> text);
        assertEquals(1, documents.size());
        assertEquals("zolt.toml", documents.get(0).relativePath());
        assertTrue(documents.get(0).contents().contains("version = \"1.2.3\""), documents.get(0)::contents);
    }

    private void writeMavenReactor() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.acme</groupId>
                  <artifactId>demo-parent</artifactId>
                  <version>1.0.0</version>
                  <packaging>pom</packaging>
                  <modules>
                    <module>service</module>
                  </modules>
                </project>
                """);
        Path service = tempDir.resolve("service");
        Files.createDirectories(service);
        Files.writeString(service.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <parent>
                    <groupId>com.acme</groupId>
                    <artifactId>demo-parent</artifactId>
                    <version>1.0.0</version>
                  </parent>
                  <artifactId>service</artifactId>
                </project>
                """);
    }

    private static EmitRenderer renderer() {
        return new EmitRenderer(
                new InspectionToManifest(),
                new DraftZoltTomlRenderer(),
                new DraftWorkspaceRenderer(),
                new FakeManifestRenderer());
    }

    /**
     * Stands in for the canonical writer. A workspace root and a project are the same authored shape in
     * the final language, so the fake branches on the {@code [workspace]} domain; each identity value is
     * emitted only when authored, mirroring the sparse output the real writer produces.
     */
    private static final class FakeManifestRenderer implements AuthoredManifestRenderer {
        @Override
        public String render(AuthoredManifest manifest) {
            return manifest.workspace()
                    .map(FakeManifestRenderer::renderWorkspace)
                    .orElseGet(() -> renderProject(manifest));
        }

        private static String renderWorkspace(AuthoredWorkspace workspace) {
            String members = workspace.members().include().stream()
                    .map(member -> "\"" + member.value() + "\"")
                    .collect(Collectors.joining(", "));
            return """
                    [workspace]
                    name = "%s"
                    members = [%s]
                    """.formatted(workspace.name().value(), members);
        }

        private static String renderProject(AuthoredManifest manifest) {
            AuthoredProjectIdentity identity = manifest.project().orElseThrow().identity();
            StringBuilder out = new StringBuilder("[project]\n");
            out.append("name = \"").append(identity.name().value()).append("\"\n");
            identity.version().ifPresent(value -> out.append("version = \"").append(value.value()).append("\"\n"));
            identity.group().ifPresent(value -> out.append("group = \"").append(value.value()).append("\"\n"));
            identity.javaRelease().ifPresent(value -> out.append("java = ").append(value.value()).append('\n'));
            return out.toString();
        }
    }
}
