package sh.zolt.explain.emit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.dependency.DependencyLane;
import sh.zolt.explain.maven.MavenInspectionResult;
import sh.zolt.explain.maven.MavenProjectInspection;
import sh.zolt.explain.maven.MavenStaticProjectInspector;
import sh.zolt.manifest.DependencyCoordinate;
import sh.zolt.manifest.WorkspaceMemberPattern;
import sh.zolt.manifest.authored.AuthoredManifest;
import sh.zolt.manifest.authored.AuthoredWorkspace;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

final class InspectionToManifestTest {
    private static final Path FIXTURE_ROOT =
            ExplainEmitTestPaths.repositoryRoot().resolve("examples/migration-explain").normalize();

    @TempDir
    private Path tempDir;

    private final InspectionToManifest mapper = new InspectionToManifest();

    @Test
    void mavenSimpleMapsScopesToDependencySections() {
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-simple"));

        DraftZoltToml draft = mapper.fromMaven(result);
        DraftManifestSubject subject = DraftManifestSubject.of(draft);

        assertEquals(Optional.of(21), subject.javaRelease());
        assertEquals("maven-simple", subject.name());
        assertTrue(subject.mainClass().isEmpty());
        assertEquals("33.4.8-jre", subject.fixed(DependencyLane.IMPLEMENTATION).get("com.google.guava:guava"));
        assertEquals("5.11.4", subject.fixed(DependencyLane.TEST).get("org.junit.jupiter:junit-jupiter"));
        assertFalse(subject.coordinates(DependencyLane.IMPLEMENTATION).contains("org.junit.jupiter:junit-jupiter"));
    }

    @Test
    void mavenSimpleIsDeterministicAcrossRuns() {
        MavenStaticProjectInspector inspector = new MavenStaticProjectInspector();
        AuthoredManifestRenderer renderer = new FakeRenderer();
        DraftZoltTomlRenderer draftRenderer = new DraftZoltTomlRenderer();

        String first = draftRenderer.render(mapper.fromMaven(inspector.inspect(FIXTURE_ROOT.resolve("maven-simple"))), renderer);
        String second = draftRenderer.render(mapper.fromMaven(inspector.inspect(FIXTURE_ROOT.resolve("maven-simple"))), renderer);

        assertEquals(first, second);
    }

    @Test
    void renderedDraftBeginsWithReviewBeforeUseNotice() {
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-simple"));
        String rendered = new DraftZoltTomlRenderer().render(mapper.fromMaven(result), new FakeRenderer());

        assertTrue(rendered.startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"));
        assertTrue(rendered.contains("# Review before use:"));
        assertTrue(rendered.contains("<<manifest>>"));
    }

    @Test
    void mavenMultiModuleEmitsWorkspaceWithMembers() {
        MavenInspectionResult result =
                new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-multimodule"));

        // : a reactor now maps to a workspace (root [workspace] + per-member drafts),
        // not a single root draft with a "map each module by hand" comment.
        DraftEmit emit = mapper.emitFromMaven(result);

        DraftWorkspace workspace = assertInstanceOf(DraftWorkspace.class, emit, () -> "expected a workspace: " + emit);
        AuthoredWorkspace root = workspace.root().workspace().orElseThrow();
        assertEquals("maven-multimodule", root.name().value());
        List<String> include = root.members().include().stream()
                .map(WorkspaceMemberPattern::value)
                .toList();
        assertTrue(include.contains("app"),
                () -> "the app module should be a workspace member: " + include);
    }

    //  -------------------------------------------------------------------------------

    @Test
    void mavenDraftEmitsDependencyExclusions() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.example</groupId>
                  <artifactId>demo</artifactId>
                  <version>1.0.0</version>
                  <dependencies>
                    <dependency>
                      <groupId>com.google.guava</groupId>
                      <artifactId>guava</artifactId>
                      <version>33.2.1-jre</version>
                      <exclusions>
                        <exclusion>
                          <groupId>com.google.code.findbugs</groupId>
                          <artifactId>jsr305</artifactId>
                        </exclusion>
                        <exclusion>
                          <groupId>org.checkerframework</groupId>
                          <artifactId>checker-qual</artifactId>
                        </exclusion>
                      </exclusions>
                    </dependency>
                  </dependencies>
                </project>
                """);

        DraftZoltToml draft = mapper.fromMaven(new MavenStaticProjectInspector().inspect(tempDir));
        DraftManifestSubject subject = DraftManifestSubject.of(draft);

        // An exclusion is one exact `group:artifact` coordinate now, not a (group, artifact) pair.
        List<String> exclusions = subject
                .dependency(DependencyLane.IMPLEMENTATION, "com.google.guava:guava")
                .metadata()
                .exclusions()
                .stream()
                .map(DependencyCoordinate::value)
                .toList();
        assertEquals(2, exclusions.size(), () -> "guava exclusions should be recorded: " + exclusions);
        assertTrue(exclusions.contains("com.google.code.findbugs:jsr305"),
                () -> "missing the findbugs exclusion: " + exclusions);
        assertTrue(exclusions.contains("org.checkerframework:checker-qual"),
                () -> "missing the checkerframework exclusion: " + exclusions);
    }

    //  -------------------------------------------------------------------------------

    @Test
    void mavenDraftEmitsRealGroupAndVersionWithoutCannotReadNote() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.acme.widgets</groupId>
                  <artifactId>widget-catalog</artifactId>
                  <version>2.3.1</version>
                  <name>Widget Catalog</name>
                </project>
                """);

        DraftZoltToml draft = mapper.fromMaven(new MavenStaticProjectInspector().inspect(tempDir));
        DraftManifestSubject subject = DraftManifestSubject.of(draft);

        assertEquals(Optional.of("com.acme.widgets"), subject.group());
        assertEquals(Optional.of("2.3.1"), subject.version());
        assertEquals("widget-catalog", subject.name());
        assertFalse(
                draft.notes().stream().anyMatch(note -> note.contains("could not be read")),
                () -> "no cannot-read note when group/version are present: " + draft.notes());
    }

    @Test
    void mavenDraftInterpolatesProjectVersion() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.acme.widgets</groupId>
                  <artifactId>widget-catalog</artifactId>
                  <version>${revision}</version>
                  <properties>
                    <revision>4.5.6</revision>
                  </properties>
                </project>
                """);

        DraftManifestSubject subject = DraftManifestSubject.of(
                mapper.fromMaven(new MavenStaticProjectInspector().inspect(tempDir)));

        assertEquals(Optional.of("4.5.6"), subject.version());
    }

    @Test
    void mavenDraftFallsBackAndCommentsWhenGroupVersionAbsent() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <artifactId>bare</artifactId>
                </project>
                """);

        DraftZoltToml draft = mapper.fromMaven(new MavenStaticProjectInspector().inspect(tempDir));
        DraftManifestSubject subject = DraftManifestSubject.of(draft);

        assertEquals(Optional.of("com.example"), subject.group());
        assertEquals(Optional.of("0.1.0"), subject.version());
        assertTrue(
                draft.notes().stream().anyMatch(note -> note.contains("group could not be read")),
                () -> "expected the cannot-read group note: " + draft.notes());
        assertTrue(
                draft.notes().stream().anyMatch(note -> note.contains("version could not be read")),
                () -> "expected the cannot-read version note: " + draft.notes());
    }

    //  -------------------------------------------------------------------------------

    @Test
    void mavenChildInheritingParentManagementEmitsConcreteVersions() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.example</groupId>
                  <artifactId>root</artifactId>
                  <version>2.0.0</version>
                  <packaging>pom</packaging>
                  <modules>
                    <module>service</module>
                  </modules>
                  <properties>
                    <maven.compiler.release>17</maven.compiler.release>
                    <jackson.version>2.17.1</jackson.version>
                  </properties>
                  <dependencyManagement>
                    <dependencies>
                      <dependency>
                        <groupId>com.fasterxml.jackson.core</groupId>
                        <artifactId>jackson-databind</artifactId>
                        <version>${jackson.version}</version>
                      </dependency>
                      <dependency>
                        <groupId>org.junit.jupiter</groupId>
                        <artifactId>junit-jupiter</artifactId>
                        <version>5.11.4</version>
                        <scope>test</scope>
                      </dependency>
                    </dependencies>
                  </dependencyManagement>
                </project>
                """);
        Path service = tempDir.resolve("service");
        Files.createDirectories(service);
        Files.writeString(service.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <parent>
                    <groupId>com.example</groupId>
                    <artifactId>root</artifactId>
                    <version>2.0.0</version>
                  </parent>
                  <artifactId>service</artifactId>
                  <dependencies>
                    <dependency>
                      <groupId>com.fasterxml.jackson.core</groupId>
                      <artifactId>jackson-databind</artifactId>
                    </dependency>
                    <dependency>
                      <groupId>org.junit.jupiter</groupId>
                      <artifactId>junit-jupiter</artifactId>
                      <scope>test</scope>
                    </dependency>
                  </dependencies>
                </project>
                """);

        MavenInspectionResult reactor = new MavenStaticProjectInspector().inspect(tempDir);
        // Emit the child module on its own (mirrors per-module emit): the mapper reads projects.get(0).
        MavenProjectInspection child = reactor.projects().stream()
                .filter(project -> project.artifactId().equals("service"))
                .findFirst()
                .orElseThrow();
        DraftZoltToml draft = mapper.fromMaven(
                new MavenInspectionResult(service, List.of(child), List.of()));
        DraftManifestSubject subject = DraftManifestSubject.of(draft);

        assertEquals(Optional.of(17), subject.javaRelease(), "child inherits the parent java version");
        assertEquals(Optional.of("2.0.0"), subject.version());
        assertEquals(Optional.of("com.example"), subject.group());
        assertEquals("2.17.1",
                subject.fixed(DependencyLane.IMPLEMENTATION).get("com.fasterxml.jackson.core:jackson-databind"),
                () -> "the implementation lane must carry the inherited concrete version: "
                        + subject.fixed(DependencyLane.IMPLEMENTATION));
        assertEquals("5.11.4", subject.fixed(DependencyLane.TEST).get("org.junit.jupiter:junit-jupiter"),
                () -> "the test lane must carry the inherited concrete version: "
                        + subject.fixed(DependencyLane.TEST));
        assertFalse(subject.coordinates(DependencyLane.IMPLEMENTATION).isEmpty(),
                "the implementation lane must not be empty");
        assertFalse(subject.coordinates(DependencyLane.TEST).isEmpty(), "the test lane must not be empty");
        assertFalse(
                draft.notes().stream().anyMatch(note -> note.contains("no static version")),
                () -> "no false version-less review comments for parent-managed deps: " + draft.notes());
    }

    //  -------------------------------------------------------------------------------

    @Test
    void mavenDraftPlacesManagedScopeDependencyInTestDependencies() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.example</groupId>
                  <artifactId>demo</artifactId>
                  <version>1.0.0</version>
                  <dependencyManagement>
                    <dependencies>
                      <dependency>
                        <groupId>org.mockito</groupId>
                        <artifactId>mockito-inline</artifactId>
                        <version>4.11.0</version>
                        <scope>test</scope>
                      </dependency>
                    </dependencies>
                  </dependencyManagement>
                  <dependencies>
                    <dependency>
                      <groupId>org.mockito</groupId>
                      <artifactId>mockito-inline</artifactId>
                    </dependency>
                  </dependencies>
                </project>
                """);

        DraftManifestSubject subject = DraftManifestSubject.of(
                mapper.fromMaven(new MavenStaticProjectInspector().inspect(tempDir)));

        assertEquals("4.11.0", subject.fixed(DependencyLane.TEST).get("org.mockito:mockito-inline"),
                () -> "the test lane must carry the dependencyManagement scope: "
                        + subject.fixed(DependencyLane.TEST));
        assertFalse(subject.coordinates(DependencyLane.IMPLEMENTATION).contains("org.mockito:mockito-inline"),
                () -> "scope-less dependency managed as test must not leak into the implementation lane: "
                        + subject.coordinates(DependencyLane.IMPLEMENTATION));
    }

    private static final class FakeRenderer implements AuthoredManifestRenderer {
        @Override
        public String render(AuthoredManifest manifest) {
            return "<<manifest>>\n";
        }
    }
}
