[workspace]
name = "slf4j-canary"

[workspace.members]
default = ["slf4j-simple"]
include = ["slf4j-api", "slf4j-simple"]

[workspace.project]
group = "org.slf4j"
version = "0.1.0"
java = 8
license = "MIT"
