[project]
name = "vertx-postgres-crud"
version = "0.1.0"
group = "com.example"
java = 21
main = "com.example.vertx.postgres.VertxPostgresCrudApplication"

[platforms]
"io.vertx:vertx-stack-depchain" = "4.5.11"

[dependencies]
"io.vertx:vertx-core" = { managed = true, exclude = ["io.netty:netty-tcnative-boringssl-static"] }
"io.vertx:vertx-pg-client" = { managed = true }
"io.vertx:vertx-web" = { managed = true }
"org.slf4j:slf4j-simple" = "2.0.17"

[dependencies.runtime]
"com.ongres.scram:client" = "2.1"

[dependencies.test]
"org.junit.jupiter:junit-jupiter" = "5.11.4"
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"

[native]
args = [
    "--no-fallback",
    "--initialize-at-run-time=io.netty.channel,io.netty.handler.ssl,io.netty.util.internal.shaded.org.jctools.util.UnsafeLongArrayAccess",
    "--initialize-at-build-time=io.netty.buffer.UnpooledByteBufAllocator,io.netty.buffer.AbstractByteBufAllocator,io.netty.buffer.Unpooled,io.netty.buffer.EmptyByteBuf,io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess,org.slf4j",
]
