[project]
name = "zolt-junit-client"

[dependencies]
"sh.zolt:zolt-test-model" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = { versionRef = "junit-platform" }
