[project]
name = "vertx-http"
version = "0.1.0"
group = "com.example"
java = 21
main = "com.example.vertx.VertxHttpApplication"

[platforms]
"io.vertx:vertx-stack-depchain" = "4.5.11"

[dependencies]
"io.vertx:vertx-core" = { managed = true, exclude = ["io.netty:netty-tcnative-boringssl-static"] }
"org.slf4j:slf4j-simple" = "2.0.17"

[dependencies.test]
"org.junit.jupiter:junit-jupiter" = "5.11.4"
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"

[build.metadata]
reproducible = true
