[project]
name = "zolt-javac-worker"
main = "sh.zolt.javac.JavacWorkerMain"

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = { versionRef = "junit-platform" }

[package]
mode = "uber-jar"
