[project]
name = "quarkus-http"
version = "0.1.0"
group = "com.example"
java = 21

[platforms]
"io.quarkus.platform:quarkus-bom" = "3.33.2"

[dependencies]
"io.quarkus:quarkus-rest" = { managed = true }

[dependencies.test]
"org.junit.jupiter:junit-jupiter" = { managed = true }

[package]
mode = "quarkus"
