package sh.zolt.cli.insight;

import static sh.zolt.cli.CliTestSupport.execute;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.cli.CliTestRepository;
import sh.zolt.cli.CliTestSupport.CommandResult;
import sh.zolt.dependency.DependencyLane;
import sh.zolt.manifest.DependencyConstraintSelector;
import sh.zolt.manifest.DependencyCoordinate;
import sh.zolt.manifest.DependencySelector;
import sh.zolt.manifest.PlatformSelector;
import sh.zolt.manifest.authored.AuthoredDependencies;
import sh.zolt.manifest.authored.AuthoredDependency;
import sh.zolt.manifest.authored.AuthoredManifest;
import sh.zolt.toml.manifest.adapter.ManifestProjectConfigLoader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

final class ExplainCommandEmitTomlTest {
    private static final ManifestProjectConfigLoader LOADER = new ManifestProjectConfigLoader();

    private static final String MAVEN_SIMPLE_POM = """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>dev.zolt.examples</groupId>
              <artifactId>maven-simple</artifactId>
              <version>1.0.0</version>
              <properties>
                <maven.compiler.release>21</maven.compiler.release>
              </properties>
              <dependencies>
                <dependency>
                  <groupId>com.google.guava</groupId>
                  <artifactId>guava</artifactId>
                  <version>33.4.8-jre</version>
                </dependency>
                <dependency>
                  <groupId>org.junit.jupiter</groupId>
                  <artifactId>junit-jupiter</artifactId>
                  <version>5.11.4</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """;

    @TempDir
    private Path tempDir;

    @Test
    void emitsDraftTomlWithNoticeAndScopedDependencies() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

        assertEquals(0, result.exitCode());
        assertEquals("", result.stderr());
        assertTrue(
                result.stdout().startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"),
                () -> "missing review notice in:\n" + result.stdout());
        assertTrue(result.stdout().contains("[project]"));
        assertTrue(result.stdout().contains("java = 21"));
        assertTrue(result.stdout().contains("[dependencies]"));
        assertTrue(result.stdout().contains("\"com.google.guava:guava\" = \"33.4.8-jre\""));
        assertTrue(result.stdout().contains("[dependencies.test]"));
        assertTrue(result.stdout().contains("\"org.junit.jupiter:junit-jupiter\" = \"5.11.4\""));
    }

    @Test
    void emittedDraftRoundTripsThroughTheFinalLoader() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        assertEquals(0, result.exitCode());

        AuthoredManifest parsed = parse(result.stdout());

        assertEquals(21, parsed.project().orElseThrow().identity().javaRelease().orElseThrow().value());
        assertEquals(
                "33.4.8-jre",
                fixedVersion(parsed, DependencyLane.IMPLEMENTATION, "com.google.guava:guava"));
        assertEquals(
                "5.11.4",
                fixedVersion(parsed, DependencyLane.TEST, "org.junit.jupiter:junit-jupiter"));
        assertFalse(
                has(parsed, DependencyLane.IMPLEMENTATION, "org.junit.jupiter:junit-jupiter"),
                () -> "the test dependency must stay in the test lane: " + declarations(parsed));
    }

    @Test
    void emitTomlOmitsUnknownMavenJavaVersion() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>dev.zolt.examples</groupId>
                  <artifactId>unknown-java</artifactId>
                  <version>1.0.0</version>
                  <build>
                    <plugins>
                      <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <executions>
                          <execution>
                            <configuration>
                              <source>8</source>
                              <target>8</target>
                            </configuration>
                          </execution>
                        </executions>
                      </plugin>
                    </plugins>
                  </build>
                </project>
                """);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

        assertEquals(0, result.exitCode(), () -> result.stderr());
        assertEquals("", result.stderr());
        assertTrue(result.stdout().contains("# Review items:"), () -> result.stdout());
        assertTrue(result.stdout().contains("Project Java version could not be determined"), () -> result.stdout());
        assertTrue(result.stdout().contains("add `[project].java`"), () -> result.stdout());
        assertFalse(hasJavaAssignment(result.stdout()), () -> result.stdout());
    }

    @Test
    void emitTomlOmitsUnknownGradleJavaVersion() throws IOException {
        Files.writeString(tempDir.resolve("settings.gradle"), "rootProject.name = 'unknown-gradle'\n");
        Files.writeString(tempDir.resolve("build.gradle"), "plugins { id 'java' }\n");

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "gradle");

        assertEquals(0, result.exitCode(), () -> result.stderr());
        assertEquals("", result.stderr());
        assertTrue(result.stdout().contains("# Review items:"), () -> result.stdout());
        assertTrue(result.stdout().contains("Project Java version could not be determined"), () -> result.stdout());
        assertTrue(result.stdout().contains("add `[project].java`"), () -> result.stdout());
        assertFalse(hasJavaAssignment(result.stdout()), () -> result.stdout());
    }

    @Test
    void emitTomlIsByteForByteDeterministic() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult first = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        CommandResult second = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        CommandResult explicitText = execute(
                "explain",
                "--emit-toml",
                "--format", "text",
                "--cwd", tempDir.toString(),
                "--source", "maven");

        assertEquals(0, first.exitCode());
        assertEquals(first.stdout(), second.stdout());
        assertEquals(0, explicitText.exitCode());
        assertEquals(first.stdout(), explicitText.stdout());
    }

    @Test
    void emitTomlConflictsWithScorecard() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result =
                execute("explain", "--emit-toml", "--scorecard", "--cwd", tempDir.toString(), "--source", "maven");

        assertNotEquals(0, result.exitCode());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--scorecard"));
    }

    @Test
    void emitTomlConflictsWithBlockers() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result =
                execute("explain", "--emit-toml", "--blockers", "--cwd", tempDir.toString(), "--source", "maven");

        assertNotEquals(0, result.exitCode());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--blockers"));
    }

    @Test
    void emitTomlConflictsWithJsonFormatForMaven() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute(
                "explain",
                "--emit-toml",
                "--format", "json",
                "--cwd", tempDir.toString(),
                "--source", "maven");

        assertEquals(2, result.exitCode());
        assertEquals("", result.stdout());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--format json"));
        assertTrue(result.stderr().contains("Choose one"));
    }

    @Test
    void emitTomlConflictsWithJsonFormatForGradle() throws IOException {
        Files.writeString(tempDir.resolve("build.gradle"), "plugins { id 'java' }\n");

        CommandResult result = execute(
                "explain",
                "--emit-toml",
                "--format", "json",
                "--cwd", tempDir.toString(),
                "--source", "gradle");

        assertEquals(2, result.exitCode());
        assertEquals("", result.stdout());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--format json"));
        assertTrue(result.stderr().contains("Choose one"));
    }

    //  / 1553 / 1554 end-to-end -----------------------------------------------------

    private static final String MAVEN_PROPERTY_POM = """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>com.acme.widgets</groupId>
              <artifactId>widget-catalog</artifactId>
              <version>2.3.1</version>
              <name>Widget Catalog</name>
              <properties>
                <maven.compiler.release>17</maven.compiler.release>
                <jackson.version>2.17.1</jackson.version>
                <guava.version>33.2.1-jre</guava.version>
                <junit.version>5.10.2</junit.version>
              </properties>
              <dependencyManagement>
                <dependencies>
                  <dependency>
                    <groupId>org.junit</groupId>
                    <artifactId>junit-bom</artifactId>
                    <version>${junit.version}</version>
                    <type>pom</type>
                    <scope>import</scope>
                  </dependency>
                </dependencies>
              </dependencyManagement>
              <dependencies>
                <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-databind</artifactId>
                  <version>${jackson.version}</version>
                </dependency>
                <dependency>
                  <groupId>com.google.guava</groupId>
                  <artifactId>guava</artifactId>
                  <version>${guava.version}</version>
                  <exclusions>
                    <exclusion>
                      <groupId>com.google.code.findbugs</groupId>
                      <artifactId>jsr305</artifactId>
                    </exclusion>
                    <exclusion>
                      <groupId>org.checkerframework</groupId>
                      <artifactId>checker-qual</artifactId>
                    </exclusion>
                  </exclusions>
                </dependency>
                <dependency>
                  <groupId>org.junit.jupiter</groupId>
                  <artifactId>junit-jupiter</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """;

    private static final String MAVEN_MANAGED_POM = """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>com.example</groupId>
              <artifactId>managed-demo</artifactId>
              <version>1.0.0</version>
              <properties>
                <maven.compiler.release>21</maven.compiler.release>
              </properties>
              <dependencyManagement>
                <dependencies>
                  <dependency>
                    <groupId>org.junit</groupId>
                    <artifactId>junit-bom</artifactId>
                    <version>5.10.2</version>
                    <type>pom</type>
                    <scope>import</scope>
                  </dependency>
                  <dependency>
                    <groupId>org.apiguardian</groupId>
                    <artifactId>apiguardian-api</artifactId>
                    <version>1.1.0</version>
                  </dependency>
                </dependencies>
              </dependencyManagement>
              <dependencies>
                <dependency>
                  <groupId>org.junit.jupiter</groupId>
                  <artifactId>junit-jupiter</artifactId>
                  <scope>test</scope>
                </dependency>
                <dependency>
                  <groupId>org.jacoco</groupId>
                  <artifactId>org.jacoco.agent</artifactId>
                  <version>0.8.12</version>
                  <classifier>runtime</classifier>
                </dependency>
              </dependencies>
            </project>
            """;

    @Test
    void emitTomlInterpolatesPropertyVersionsEmitsCoordsAndExclusions() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_PROPERTY_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

        assertEquals(0, result.exitCode());
        assertEquals("", result.stderr());
        String toml = result.stdout();

        // : real project coordinates, no cannot-read comment.
        assertTrue(toml.contains("group = \"com.acme.widgets\""), () -> toml);
        assertTrue(toml.contains("version = \"2.3.1\""), () -> toml);
        assertFalse(toml.contains("could not be read"), () -> toml);

        // : interpolated concrete versions; no interpolation token survives.
        assertTrue(toml.contains("\"com.fasterxml.jackson.core:jackson-databind\" = \"2.17.1\""), () -> toml);
        assertTrue(toml.contains("\"org.junit:junit-bom\" = \"5.10.2\""), () -> toml);
        assertTrue(toml.contains("\"org.junit.jupiter:junit-jupiter\" = { managed = true }"), () -> toml);
        assertFalse(toml.contains("${"), () -> "no interpolation token should survive:\n" + toml);

        // : guava's exclusions carried in the draft as an `exclude` coordinate array.
        assertTrue(toml.contains("\"com.google.guava:guava\" = { version = \"33.2.1-jre\", exclude = ["), () -> toml);
        assertTrue(
                toml.contains("exclude = [\"com.google.code.findbugs:jsr305\", "
                        + "\"org.checkerframework:checker-qual\"]"),
                () -> toml);
    }

    @Test
    void emitTomlWithPropertyVersionsRoundTripsThroughTheFinalLoader() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_PROPERTY_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        assertEquals(0, result.exitCode());

        AuthoredManifest parsed = parse(result.stdout());

        assertEquals("com.acme.widgets", parsed.project().orElseThrow().identity().group().orElseThrow().value());
        assertEquals("2.3.1", parsed.project().orElseThrow().identity().version().orElseThrow().value());
        assertEquals(
                "2.17.1",
                fixedVersion(parsed, DependencyLane.IMPLEMENTATION, "com.fasterxml.jackson.core:jackson-databind"));
        assertEquals(
                "33.2.1-jre",
                fixedVersion(parsed, DependencyLane.IMPLEMENTATION, "com.google.guava:guava"));
        assertEquals("5.10.2", platformVersion(parsed, "org.junit:junit-bom"));
        assertInstanceOf(
                DependencySelector.Managed.class,
                dependency(parsed, DependencyLane.TEST, "org.junit.jupiter:junit-jupiter").selector());
        assertEquals(
                List.of(
                        new DependencyCoordinate("com.google.code.findbugs:jsr305"),
                        new DependencyCoordinate("org.checkerframework:checker-qual")),
                dependency(parsed, DependencyLane.IMPLEMENTATION, "com.google.guava:guava")
                        .metadata()
                        .exclusions());
    }

    @Test
    void emitTomlCarriesDependencyManagementFactsAndResolvesDraft() throws IOException {
        try (CliTestRepository repository = CliTestRepository.start()) {
            repository.addArtifact("org.junit", "junit-bom", "5.10.2", """
                    <project>
                      <groupId>org.junit</groupId>
                      <artifactId>junit-bom</artifactId>
                      <version>5.10.2</version>
                      <packaging>pom</packaging>
                      <dependencyManagement>
                        <dependencies>
                          <dependency>
                            <groupId>org.junit.jupiter</groupId>
                            <artifactId>junit-jupiter</artifactId>
                            <version>5.10.2</version>
                          </dependency>
                          <dependency>
                            <groupId>org.junit.platform</groupId>
                            <artifactId>junit-platform-console</artifactId>
                            <version>1.11.4</version>
                          </dependency>
                        </dependencies>
                      </dependencyManagement>
                    </project>
                    """);
            repository.addArtifact("org.junit.jupiter", "junit-jupiter", "5.10.2", """
                    <project>
                      <groupId>org.junit.jupiter</groupId>
                      <artifactId>junit-jupiter</artifactId>
                      <version>5.10.2</version>
                      <dependencies>
                        <dependency>
                          <groupId>org.apiguardian</groupId>
                          <artifactId>apiguardian-api</artifactId>
                          <version>1.1.2</version>
                        </dependency>
                      </dependencies>
                    </project>
                    """);
            repository.addArtifact("org.apiguardian", "apiguardian-api", "1.1.0", """
                    <project>
                      <groupId>org.apiguardian</groupId>
                      <artifactId>apiguardian-api</artifactId>
                      <version>1.1.0</version>
                    </project>
                    """);
            repository.addArtifact("org.apiguardian", "apiguardian-api", "1.1.2", """
                    <project>
                      <groupId>org.apiguardian</groupId>
                      <artifactId>apiguardian-api</artifactId>
                      <version>1.1.2</version>
                    </project>
                    """);
            repository.addArtifact("org.junit.platform", "junit-platform-console", "1.11.4", """
                    <project>
                      <groupId>org.junit.platform</groupId>
                      <artifactId>junit-platform-console</artifactId>
                      <version>1.11.4</version>
                    </project>
                    """);
            Files.writeString(tempDir.resolve("pom.xml"), MAVEN_MANAGED_POM);

            CommandResult explain = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

            assertEquals(0, explain.exitCode(), () -> explain.stderr());
            AuthoredManifest parsed = parse(explain.stdout());
            assertEquals("5.10.2", platformVersion(parsed, "org.junit:junit-bom"));
            assertInstanceOf(
                    DependencySelector.Managed.class,
                    dependency(parsed, DependencyLane.TEST, "org.junit.jupiter:junit-jupiter").selector());
            assertEquals("1.1.0", constraintVersion(parsed, "org.apiguardian:apiguardian-api"));
            assertFalse(
                    has(parsed, DependencyLane.IMPLEMENTATION, "org.jacoco:org.jacoco.agent"),
                    () -> "a classifier dependency stays a review note: " + declarations(parsed));
            assertTrue(explain.stdout().contains("classifier `runtime`"), () -> explain.stdout());

            Files.writeString(tempDir.resolve("zolt.toml"), withCentralMirror(explain.stdout(), repository));
            CommandResult resolve = execute(
                    "resolve",
                    "--cwd", tempDir.toString(),
                    "--cache-root", tempDir.resolve("cache").toString());

            assertEquals(0, resolve.exitCode(), () -> resolve.stderr());
            String lock = Files.readString(tempDir.resolve("zolt.lock"));
            assertTrue(lock.contains("org.apiguardian:apiguardian-api:1.1.0"), () -> lock);
            assertFalse(lock.contains("org.apiguardian:apiguardian-api:1.1.2"), () -> lock);
            assertTrue(lock.contains(
                    "id = \"org.junit.platform:junit-platform-console\"\nversion = \"1.11.4\""), () -> lock);
        }
    }

    /**
     * The final language never authors {@code [repositories]} in a draft, so a draft inherits Maven
     * Central. Pointing a resolve at the hermetic test repository is an explicit Central mirror
     * appended to the emitted document.
     */
    private static String withCentralMirror(String manifest, CliTestRepository repository) {
        return manifest + """

                [repositories]
                central = "%s"
                """.formatted(repository.baseUri());
    }

    private static AuthoredManifest parse(String emitted) {
        return LOADER.document(emitted).authored();
    }

    private static List<AuthoredDependency> declarations(AuthoredManifest manifest) {
        return manifest.dependencies().map(AuthoredDependencies::declarations).orElse(List.of());
    }

    private static boolean has(AuthoredManifest manifest, DependencyLane lane, String coordinate) {
        return declarations(manifest).stream()
                .anyMatch(entry -> entry.lane() == lane && entry.coordinate().value().equals(coordinate));
    }

    private static AuthoredDependency dependency(
            AuthoredManifest manifest, DependencyLane lane, String coordinate) {
        return declarations(manifest).stream()
                .filter(entry -> entry.lane() == lane && entry.coordinate().value().equals(coordinate))
                .findFirst()
                .orElseThrow(() -> new AssertionError(
                        "No " + lane + " dependency on `" + coordinate + "` in " + declarations(manifest)));
    }

    private static String fixedVersion(
            AuthoredManifest manifest, DependencyLane lane, String coordinate) {
        return assertInstanceOf(
                        DependencySelector.FixedVersion.class,
                        dependency(manifest, lane, coordinate).selector())
                .value();
    }

    private static String platformVersion(AuthoredManifest manifest, String coordinate) {
        PlatformSelector selector = manifest.platforms()
                .orElseThrow()
                .entries()
                .get(new DependencyCoordinate(coordinate));
        return assertInstanceOf(PlatformSelector.FixedVersion.class, selector).value();
    }

    private static String constraintVersion(AuthoredManifest manifest, String coordinate) {
        DependencyConstraintSelector selector = manifest.dependencyConstraints()
                .orElseThrow()
                .entries()
                .get(new DependencyCoordinate(coordinate))
                .selector();
        return assertInstanceOf(DependencyConstraintSelector.FixedVersion.class, selector).value();
    }

    /** True when any line, live or commented out, still assigns {@code [project].java}. */
    private static boolean hasJavaAssignment(String rendered) {
        return rendered.lines()
                .map(String::strip)
                .map(line -> line.startsWith("#") ? line.substring(1).strip() : line)
                .anyMatch(line -> line.startsWith("java ="));
    }
}
