package sh.zolt.cli.insight;

import static sh.zolt.cli.CliTestSupport.execute;
import static sh.zolt.cli.insight.EmitTomlManifests.declarations;
import static sh.zolt.cli.insight.EmitTomlManifests.fixedVersion;
import static sh.zolt.cli.insight.EmitTomlManifests.has;
import static sh.zolt.cli.insight.EmitTomlManifests.parse;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.cli.CliTestSupport.CommandResult;
import sh.zolt.dependency.DependencyLane;
import sh.zolt.manifest.authored.AuthoredManifest;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

final class ExplainCommandEmitTomlTest {
    private static final String MAVEN_SIMPLE_POM = """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>dev.zolt.examples</groupId>
              <artifactId>maven-simple</artifactId>
              <version>1.0.0</version>
              <properties>
                <maven.compiler.release>21</maven.compiler.release>
              </properties>
              <dependencies>
                <dependency>
                  <groupId>com.google.guava</groupId>
                  <artifactId>guava</artifactId>
                  <version>33.4.8-jre</version>
                </dependency>
                <dependency>
                  <groupId>org.junit.jupiter</groupId>
                  <artifactId>junit-jupiter</artifactId>
                  <version>5.11.4</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """;

    @TempDir
    private Path tempDir;

    @Test
    void emitsDraftTomlWithNoticeAndScopedDependencies() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

        assertEquals(0, result.exitCode());
        assertEquals("", result.stderr());
        assertTrue(
                result.stdout().startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"),
                () -> "missing review notice in:\n" + result.stdout());
        assertTrue(result.stdout().contains("[project]"));
        assertTrue(result.stdout().contains("java = 21"));
        assertTrue(result.stdout().contains("[dependencies]"));
        assertTrue(result.stdout().contains("\"com.google.guava:guava\" = \"33.4.8-jre\""));
        assertTrue(result.stdout().contains("[dependencies.test]"));
        assertTrue(result.stdout().contains("\"org.junit.jupiter:junit-jupiter\" = \"5.11.4\""));
    }

    @Test
    void emittedDraftRoundTripsThroughTheFinalLoader() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        assertEquals(0, result.exitCode());

        AuthoredManifest parsed = parse(result.stdout());

        assertEquals(21, parsed.project().orElseThrow().identity().javaRelease().orElseThrow().value());
        assertEquals(
                "33.4.8-jre",
                fixedVersion(parsed, DependencyLane.IMPLEMENTATION, "com.google.guava:guava"));
        assertEquals(
                "5.11.4",
                fixedVersion(parsed, DependencyLane.TEST, "org.junit.jupiter:junit-jupiter"));
        assertFalse(
                has(parsed, DependencyLane.IMPLEMENTATION, "org.junit.jupiter:junit-jupiter"),
                () -> "the test dependency must stay in the test lane: " + declarations(parsed));
    }

    @Test
    void emitTomlOmitsUnknownMavenJavaVersion() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>dev.zolt.examples</groupId>
                  <artifactId>unknown-java</artifactId>
                  <version>1.0.0</version>
                  <build>
                    <plugins>
                      <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <executions>
                          <execution>
                            <configuration>
                              <source>8</source>
                              <target>8</target>
                            </configuration>
                          </execution>
                        </executions>
                      </plugin>
                    </plugins>
                  </build>
                </project>
                """);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

        assertEquals(0, result.exitCode(), () -> result.stderr());
        assertEquals("", result.stderr());
        assertTrue(result.stdout().contains("# Review items:"), () -> result.stdout());
        assertTrue(result.stdout().contains("Project Java version could not be determined"), () -> result.stdout());
        assertTrue(result.stdout().contains("add `[project].java`"), () -> result.stdout());
        assertFalse(hasJavaAssignment(result.stdout()), () -> result.stdout());
    }

    @Test
    void emitTomlOmitsUnknownGradleJavaVersion() throws IOException {
        Files.writeString(tempDir.resolve("settings.gradle"), "rootProject.name = 'unknown-gradle'\n");
        Files.writeString(tempDir.resolve("build.gradle"), "plugins { id 'java' }\n");

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "gradle");

        assertEquals(0, result.exitCode(), () -> result.stderr());
        assertEquals("", result.stderr());
        assertTrue(result.stdout().contains("# Review items:"), () -> result.stdout());
        assertTrue(result.stdout().contains("Project Java version could not be determined"), () -> result.stdout());
        assertTrue(result.stdout().contains("add `[project].java`"), () -> result.stdout());
        assertFalse(hasJavaAssignment(result.stdout()), () -> result.stdout());
    }

    @Test
    void emitTomlIsByteForByteDeterministic() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult first = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        CommandResult second = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        CommandResult explicitText = execute(
                "explain",
                "--emit-toml",
                "--format", "text",
                "--cwd", tempDir.toString(),
                "--source", "maven");

        assertEquals(0, first.exitCode());
        assertEquals(first.stdout(), second.stdout());
        assertEquals(0, explicitText.exitCode());
        assertEquals(first.stdout(), explicitText.stdout());
    }

    @Test
    void emitTomlConflictsWithScorecard() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result =
                execute("explain", "--emit-toml", "--scorecard", "--cwd", tempDir.toString(), "--source", "maven");

        assertNotEquals(0, result.exitCode());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--scorecard"));
    }

    @Test
    void emitTomlConflictsWithBlockers() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result =
                execute("explain", "--emit-toml", "--blockers", "--cwd", tempDir.toString(), "--source", "maven");

        assertNotEquals(0, result.exitCode());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--blockers"));
    }

    @Test
    void emitTomlConflictsWithJsonFormatForMaven() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute(
                "explain",
                "--emit-toml",
                "--format", "json",
                "--cwd", tempDir.toString(),
                "--source", "maven");

        assertEquals(2, result.exitCode());
        assertEquals("", result.stdout());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--format json"));
        assertTrue(result.stderr().contains("Choose one"));
    }

    @Test
    void emitTomlConflictsWithJsonFormatForGradle() throws IOException {
        Files.writeString(tempDir.resolve("build.gradle"), "plugins { id 'java' }\n");

        CommandResult result = execute(
                "explain",
                "--emit-toml",
                "--format", "json",
                "--cwd", tempDir.toString(),
                "--source", "gradle");

        assertEquals(2, result.exitCode());
        assertEquals("", result.stdout());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--format json"));
        assertTrue(result.stderr().contains("Choose one"));
    }

    /** True when any line, live or commented out, still assigns {@code [project].java}. */
    private static boolean hasJavaAssignment(String rendered) {
        return rendered.lines()
                .map(String::strip)
                .map(line -> line.startsWith("#") ? line.substring(1).strip() : line)
                .anyMatch(line -> line.startsWith("java ="));
    }
}
