[project]
name = "spring-boot-webmvc"
version = "0.1.0"
group = "com.example"
java = 21
main = "com.example.springboot.DemoApplication"

[platforms]
"org.springframework.boot:spring-boot-dependencies" = "4.0.6"

[dependencies]
"org.springframework.boot:spring-boot-starter-webmvc" = { managed = true }

[dependencies.test]
"org.springframework.boot:spring-boot-starter-test" = { managed = true }

[build.metadata]
buildInfo = true
git = true
reproducible = true

[resources]
main = ["src/main/resources", "target/generated/resources"]

[package]
mode = "spring-boot"
