[project]
name = "zolt-toolchain"

[dependencies]
"com.fasterxml.jackson.core:jackson-core" = "2.22.2"
"sh.zolt:zolt-model" = { workspace = true }
"sh.zolt:zolt-toml" = { workspace = true }

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"
