[project]
name = "junit-vintage"
version = "0.1.0"
group = "com.example"
java = 21

[dependencies.test]
"junit:junit" = "4.13.2"
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"
"org.junit.vintage:junit-vintage-engine" = "5.11.4"
